[package]
name = "wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
image = "0.25.1"
wasm-bindgen = "0.2.92"
core_lib = { path = "../core_lib" }
flatbuffers = "24.3.25"

[dependencies.web-sys]
version = "0.3"
features = ["console"]
